### ISSUE TITLE
Cannot find module 'redux-observable' from 'redux-tdd.js'

### ISSUE THREAD

**Issue by amf9t2** [lmatteis/redux-tdd#2]
I have installed redux-tdd, can see the redux-tdd folder inside node_modules. But running the test gives me error "Cannot find module 'redux-observable' from 'redux-tdd.js'".

Am I doing something wrong ?

```
import React from 'react';
import { shallow } from 'enzyme';
// import { Observable } from 'rxjs';
import ReduxTdd from 'redux-tdd';

import { abc, xyz } from '../actions';
import { reducer } from '../reducers';
import Page from '../ActionPlan';
import activities from '../data';

describe('Action Plan Pages', () => {
  ReduxTdd({ activities }, state => [
    <Page activities={state.activities} />,
  ])
    .simulate(wrapper => wrapper.find('a').simulate('click'));
});
```
![image](https://user-images.githubusercontent.com/6234682/34897769-6a0e8c00-f7b5-11e7-8426-5c0f4d32fca6.png)

**Comment by lmatteis** [comment]
Hey it has a peerDependency on redux-observable. Have you tried `npm install redux-observable --save-dev`?

**Comment by lmatteis** [comment]
Also that API is deprecated. Look at the docs or the test folder. You need to use `.action` instead of `.simulate`

**Comment by amf9t2** [comment]
installing redux-tdd doesn't install its peer dependency? 

I will try again as you said.
